### ISSUE TITLE
Improve performance of the pybilt.lipid_grid.lipid_grid module code.

### ISSUE THREAD

**Issue by blakeaw** [blakeaw/PyBILT#31]
The code in the pybilt.lipid_grid.lipid_grid module works okay, but the construction of the LipidGrids objects (i.e. the construction of the LipidGrid2D objects) is relatively slow and can greatly slow the analysis loop in the BilayerAnalyzer that use this object. The built in analysis functions can also be quite clunky. It would be good if this code could better optimized to improve performance and thus overall usability.

**Comment by kain88-de** [comment]
Hi  

MDAnalysis has a [GSoC student](https://summerofcode.withgoogle.com/projects/#5050592943144960) this year improving distance search. I had a short look at the code and it seems you are building a sort of cell list. With an O(N) distance search algorithm your grid code could likely be improved. A quick guess of an implementation could look like this. It should calculate for each center the id of the lipid closest to it (That is what I understood the lipid_grid  code does)

```python
# numpy array with all center positions as a (N, 3) array, with centers[:, 2] == 0
centers = ...
# returns a sparse matrix with first index giving the current center
# This assumes in another step lipid_com[:, 2] == 0 was ensured to only have xy distance
# uses an efficient O(N) algorithm (I made up the function name here!)
dist_mat = cellgrid_distance_with_cutoff(centers, lipid_com, box, max_dist)

# grid to populate.
lipid_grid = np.empty((len(x_centers), len(y_centers))
# mapping of id in centers array to the grid (N, 2)
id_centers = ...
# for each grid cell get the minimum lipid com
for i in len(centers):
    lipid_grid[id_centers[i]] = dist_mat[i].argmin()
```

If you find this useful and have time to test implementations you can drop a line on the MDAnalysis devel mailing list.

**Comment by blakeaw** [comment]
@kain88-de Yeah, that's what the lipid_grid code is doing when assigning lipids to the grid elements. Thanks for the suggestion on the O(N) distance search algorithms. I'll browse the literature, and I'll keep an eye out on Ayush's work with the distance search algorithms in MDAnalysis.

**Comment by kain88-de** [comment]
You can find the current discussions on the project [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mdnalysis-devel/NTZL8OXXlaA/qZVf7__dBgAJ). We appreciate input for good benchmarking examples.

The thread now also contains some literature for developments of the recent years.

**Comment by blakeaw** [comment]
I went ahead and closed this issue. I finally pushed and merged in some code with a updated version of the lipid_grid which is faster. See https://github.com/blakeaw/PyBILT/pull/37

**Comment by kain88-de** [comment]
FYI. The upcoming  MDAnalysis release contains a function to only calculate distances within a specified cutoff. It’s a lot faster for most workloads we have. The functions is capped_distance. Our GSoC student also did a lot of benchmarks on it over the summer.
