### ISSUE TITLE
Setup and install using Anaconda's conda tool is not working

### ISSUE THREAD

**Issue by satary** [blakeaw/PyBILT#33]
There are a couple of conflicting packages in the yaml file so ``` conda env create -f environment.yml``` does not work.
```
conda create --name pybilt
source activate pybilt
conda install -c conda-forge MDAnalysis=0.16.2 NumPy SciPy Matplotlib Seaborn libnetcdf
```
Worked for me.

**Comment by blakeaw** [comment]
Thank you @satary for raising this issue and posting your solution.

I've updated the yaml file (environment.yml), pairing down the packages to MDAnalysis=0.16.2, NumPy, SciPy, Matplotlib, Seaborn, libnetcdf, pytest, and Jupyter (along with all their dependencies). I removed the build info from the environment yaml (conda env export --no-builds), so hopefully that will fix any further issues with stale builds when regenerating the pybilt environment.

I'm going to go ahead and close this issue, but if there are any further problems with the environment dependencies or yaml files, then please comment and I'll reopen the issue. Thanks!
